# CONFIG FILE FOR AN EXPERIMENT

data_dir: '/data/GP_FBANK_ALL_39/'
speech_metadata: '/acoustic_word_embeddings/metadata/gp_spoken_words_metadata.tsv'
model_save_dir: '/acoustic_word_embeddings/inprogress_models/'
seed: 1248 #1358
language_set: 'DEU' # CZE DEU
dev_split: 'EVA' #DEV' #EVA
experiment_name: 'AWEs_2BiGRU_DEU_1024d_cls_02drop'
#
input_signal_params:
    acoustic_features: 'FBANK'
    max_num_frames: 120
    sampling_rate: 16000
#
acoustic_encoder:
    encoder_arch: 'CNN'
    spectral_dim: 39
    max_num_frames: 120
    output_dim: 1024
    pooling_type: 'avg'
    frame_dropout: False # either frame_dropout or feature_dropout can be True
    feature_dropout: False
    signal_dropout_prob: 0.0
    unit_dropout_prob: 0.2
    num_channels:
       - 256
       - 512
       - 1024
    filter_sizes:
       - 4
       - 8
       - 16
    stride_steps:
       - 1
       - 1
       - 1
#
training_hyperparams:
    learning_rate: 0.001
    batch_size: 256 
    num_epochs: 100
    early_stopping_criteria: 50
cuda: True
catch_keyboard_interrupt: True
reload_from_files: False
expand_filepaths_to_save_dir: True
