# CONFIG FILE FOR AN EXPERIMENT

data_dir: '/data/GP_FBANK_ALL_39/'
speech_metadata: '/acoustic_word_embeddings/metadata/gp_spoken_words_metadata.tsv'
model_save_dir: '/acoustic_word_embeddings/inprogress_models/'
seed: 4321 #1358
language_set: 'DEU' # CZE DEU
dev_split: 'EVA' #DEV' #EVA
experiment_name: 'AWEs_2BiGRU_DEU_1024d_cls_02drop'
#
input_signal_params:
    acoustic_features: 'FBANK'
    max_num_frames: 120
    sampling_rate: 16000

#
acoustic_encoder:
    encoder_arch: 'BiGRU'
    spectral_dim: 39
    max_num_frames: 120
    hidden_state_dim: 512
    output_dim: 1024
    n_layers: 2
    unit_dropout_prob: 0.2
    frame_dropout: False # either frame_dropout or feature_dropout can be True
    feature_dropout: False
    signal_dropout_prob: 0.0
#
training_hyperparams:
    learning_rate: 0.001
    batch_size: 256 
    num_epochs: 100
    early_stopping_criteria: 50
cuda: True
catch_keyboard_interrupt: True
reload_from_files: False
expand_filepaths_to_save_dir: True
